apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icwebapp-data-pvc
  namespace: icgroup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard