apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: icgroup
spec:
  type: NodePort
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30069 # Choisis entre 30000-32767 ou laisse vide pour auto-assign
  selector:
    app: odoo