apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: icgroup
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Postgres",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "Username": "odoo",
          "SSLMode": "prefer"
        }
      }
    }