---
- name: get kubeconfig
  hosts: dev-1
  tasks:
    - name: copy kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes
    - name: update kubeconfig
      local_action:
        module: lineinfile
        path: ./k3s.yaml
        regexp:'    server: https://127.0.0.1:6443'
        line:'    server: https://{{ ansible_host }}:6443'