apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30069
  selector:
    {{ include "icgroup.selectorLabels" "odoo" | nindent 4 }}