apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    {{ include "icgroup.selectorLabels" "pgadmin" | nindent 4 }}